<a href="https://colab.research.google.com/github/Yamuna943/internship/blob/master/internship1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
np.arange(10,30,5)

array([10, 15, 20, 25])

In [0]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from numpy import pi
>>> np.linspace( 0, 2, 9 )   

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [0]:
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [0]:
b=np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [0]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [0]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [0]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [0]:
b**2

array([0, 1, 4, 9])

In [0]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [0]:
a<35

array([ True,  True, False, False])

In [0]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [0]:
A@B

array([[5, 4],
       [3, 4]])

In [26]:
A=np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
A.ndim

2

In [27]:
B=np.array([[1,2,3,4,5],[6,7,8,9,0],[3,4,5,6,7]])
B.ndim

2

In [28]:
A*B

array([[ 0,  2,  6, 12, 20],
       [30, 42, 56, 72,  0],
       [30, 44, 60, 78, 98]])

In [0]:
A@B